document.querySelectorAll(".card").forEach((c,i)=>{
c.style.opacity=0;
c.style.transform="translateY(20px)";
setTimeout(()=>{
c.style.transition="0.5s";
c.style.opacity=1;
c.style.transform="translateY(0)";
},i*200);
});
